### ISSUE TITLE
master doesn't seem to build on os x 10.12.6 (macOS Sierra)

### ISSUE THREAD

**Issue by kcaporaso** [jmhodges/howsmyssl#218]
Downloaded go from https://golang.org/dl/ . version 1.10.1
Installed successfully.
Worked out getting the other required go packages onto OS X via ```go get```

Now, I'm faced with the following error on the latest master branch, as of this posting.

```
howsmyssl kevin$ go build
# _/Users/kevin/projects/howsmyssl
./howsmyssl.go:156:9: cannot use client.Logger(*allowLogName) (type *"cloud.google.com/go/logging".Logger) as type logClient in assignment:
	*"cloud.google.com/go/logging".Logger does not implement logClient (wrong type for Flush method)
		have Flush() error
		want Flush()
```

Any insight would be great, thank you, btw, first time using Go.

**Comment by kcaporaso** [comment]
@jmhodges thanks for the quick response.  I tried exactly what you suggested and it's the exact same error - as an extra step after your steps I removed the entire repo locally and started from scratch.  Maybe there are some incompatibilities with the go libs on OS X.  My next step will be to try on ubuntu.

**Comment by jmhodges** [comment]
I'm running on OS X with the exact same software as you are. I suspect you have an old version of the codebase, though, that I believe did could have had that error because it wasn't vendoring that library.

**Comment by jmhodges** [comment]
The only way I could get close to reproducing was by deleting the vendor directory. Are you sure you successfully checked out all of the code and didn't accidentally delete the vendor directory or enable some means of skipping it?

**Comment by jmhodges** [comment]
Toss me a `git status` and a `git remote -v` in your directory and not one that is equivalent. I strongly suspect you have a build process that forgot to copy the vendor dir over.

**Comment by kcaporaso** [comment]
```
Kevins-MacBook-Pro:howsmyssl kevin$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Kevins-MacBook-Pro:howsmyssl kevin$ git remote -v
origin	git@github.com:jmhodges/howsmyssl.git (fetch)
origin	git@github.com:jmhodges/howsmyssl.git (push)
```
Could it be that I used things like:
``` go get -u cloud.google.com/go/logging``` 
```go get -u github.com/dgryski/go-topk```
to grab missing things during the very first ```go build```
?

**Comment by jmhodges** [comment]
The problem is that the library you're loading is newer than the one that's been vendor. Could you do a `git rev-parse HEAD` and a `ls` for me in the directory you're building in?

**Comment by jmhodges** [comment]
I bet I know what the deal is. You've cloned howsmyssl outside of your GOPATH and so the vendor dir is not being used. Please move it to $GOPATH/src/github.com/jmhodges/howsmyssl (or do a `go get github.com/jmhodges/howsmyssl`) and it'll start to work

**Comment by kcaporaso** [comment]
```git rev-parse HEAD``` and ```ls```
```Kevins-MacBook-Pro:howsmyssl kevin$ git rev-parse HEAD
25d9a78743325e1ada085327acc8fd304eea41be
Kevins-MacBook-Pro:howsmyssl kevin$ ls
Dockerfile				config					stat_writer.go
LICENSE					conn.go					static
README.md				gzip					templates
all_suites.go				howsmyssl-gcloud-credentials.json.enc	tls110
allow.go				howsmyssl.go				tls_test.go
allow_test.go				index_test.go				travis_docker_push.sh
cbc_suites.go				insecure_suites.go			vendor
client_info.go				reloader.go
```

**Comment by jmhodges** [comment]
Yeah, it's gotta be the GOPATH thing

**Comment by kcaporaso** [comment]
YES! that was exactly the problem.  My GOPATH was not set, wasn't even aware of it actually.  So, I set my ```GOPATH=~/projects/go``` and then moved your repo into ```~/projects/go/src/github.com/jmhodges/howsmyssl```, then ```cd ~/projects/go/src/github.com/jmhodges/howsmyssl``` typed ```go build``` and it built.  Then ran ```./howsmyssl``` and it returned ```2018/04/27 21:29:24 Booting HTTPS on localhost:10443 and HTTP on localhost:10080```, I was able to navigate to that URL and it worked perfectly.  

Can't thank you enough, really appreciate your time on this one!  You may want to mention the GOPATH thing in the README.md.  You may get more people like me coming around since requirements are coming around to alert users of older browsers to update or else they can't transact on certain website, mainly credit card purchase related.  

Thanks again, 
Kevin
